import "@radix-ui/themes/styles.css";
import "./globals.css";
import './themeConfig.css'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "./NavBar";
import { Theme, ThemePanel ,Container } from "@radix-ui/themes";
import AuthProvider from "./auth/Provider";
import  QueryClientProvider from '@/app/QueryClientProvider'

const inter = Inter(
  { subsets: ["latin"] ,
   variable: '--font-inter'
  });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        {/* theme following component wrap the whole application so that all the radix ui can be implemented on our whole application. */}
        <QueryClientProvider>
        <AuthProvider>
        <Theme accentColor="iris" radius="large"> 
          <NavBar />
          <Container>
          <main className="p-5">{children}</main>
          </Container>
        </Theme>
        </AuthProvider>
        </QueryClientProvider> 
      </body>
    </html>
  );
}
